### PR TITLE
Fixed compilation error under gcc10

### PR DESCRIPTION
**Pull request by iblech**
Note that I'm not actually an user of CinelerraCV; I just noticed that the Nix build is failing. This patch fixes the compilation error, and I believe that the new version is what has been actually intended all along. With the patch, CinelerraCV compiles just fine and starts nicely. But I cannot judge whether it works as it should.

Thank you for your working maintaining CinelerraCV :-)

### CODE REVIEW

**Comment by j6t** [comment]
Please copy-and-paste the error message that you observe into the *commit message*.

Judging from the name "patch-narrowing" that I have seen in the context of this patch, it seems to be a narrowing error. If that is the case, it may be preferable to put a cast at the point of narrowing instead of changing `int` to `unsigned` in a lot of places. But I cannot tell if I don't know what exactly the error is.

**Comment by IgorVladimirsky** [comment]
Hi,
This is just a redirect to a mailbox of Ingo aka iblech
I put his mail on the recipient list of the thread.

IgorVLD

сб, 13 февр. 2021 г. в 02:11, Johannes Sixt <notifications@github.com>:

**Comment by iblech** [comment]
Thank you for the review! :-) I just force-pushed a new commit which contains the precise error message. Sorry, I should have done that from the beginning.

I don't believe that putting in an explicit cast would be correct, as the problematic value, `0xffffffff` (= 4294967295), is not guaranteed to be representable as a signed int (on 32 bit systems, unsigned int is `0..4294967295` while signed int is `-2147483648..2147483647`, right?).

Could you elaborate how unsigned int could create a minefield for next changes?

**Comment by IgorVladimirsky** [comment]
This fix was suggested by Einar Rünkaru and approved by Johannes Sixt. 
I have tested it under GCC 5.5.0  It is Ok for me.

Fix the line №50 in sources/cinelerra/transportque.inc
Change it from
#define CHANGE_ALL            0xffffffff
to
#define CHANGE_ALL            0xff

Ingo, can you test the fix under GCC 10.2.0 ?

**Comment by iblech** [comment]
Ah, very nice! I confirm that this patch works finen with GCC 10.2.0. I'll then consider this pull request to be obsolete and wait for the new fix to be committed, right?

**Comment by IgorVladimirsky** [comment]
The fix was pushed to the repo.
Thanks to all !

**Pull request closed without merging**
